import { Box } from '@chakra-ui/react'
import React from 'react'
import { Features } from '../Components/Features/Features'
import { Navbar } from '../Components/Navbar/Navbar'

const Home = () => {
    return (
        <Box >
            <Navbar />
            <Features />
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>

        </Box>
    )
}

export default Home
